name: ppremake CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: microsoft/setup-msbuild@v1
      if: matrix.os == 'windows-latest'

    - name: msbuild
      run: msbuild src\ppremake.sln -p:Configuration=Release
      if: matrix.os == 'windows-latest'
    
    - name: deps (linux)
      run: sudo apt-get install autotools-dev autoconf
      if: matrix.os == 'ubuntu-latest'
    
    - name: deps (macos)
      run: brew install autoconf automake libtool
      if: matrix.os == 'macos-latest'
      
    - name: configure
      run: |
        cd src
        aclocal
        autoheader
        automake --foreign -a
        autoconf
        ./configure
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      
    - name: make
      run: cd ./src && make
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      
    - name: make check
      run: cd ./src && make check
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
