name: ppremake CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    
    - name: deps (linux)
      run: |
        sudo apt-get install autotools-dev
        sudo apt-get install autoconf
      if: matrix.os == 'ubuntu-latest'
      
    - name: configure
      run: |
        cd src
        aclocal
        autoheader
        automake --foreign -a
        autoconf
        ./configure
      if: matrix.os == 'ubuntu-latest'
      
    - name: make
      run: cd ./src && make
      if: matrix.os == 'ubuntu-latest'
      
    - name: make check
      run: cd ./src && make check
      if: matrix.os == 'ubuntu-latest'
    
    - name: build (msbuild)
      run: cd ./src && msbuild ppremake.sln -p:Configuration=Release;Platform=x64
      if: matrix.os == 'windows-latest'
