name: ppremake POSIX CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    
    - name: deps (linux)
      run: sudo apt-get install autotools-dev autoconf
      if: matrix.os == 'ubuntu-latest'
    
    - name: deps (macos)
      run: brew install autoconf automake libtool
      if: matrix.os == 'macos-latest'
      
    - name: configure
      run: |
        cd src
        aclocal
        autoheader
        automake --foreign -a
        autoconf
        ./configure
      
    - name: make
      run: cd ./src && make
      
    - name: make check
      run: cd ./src && make check
